"""Signal and analysis data models for the MT5 AI Trader project.

Provides dataclass definitions for trade signals, AI-driven trade decisions,
and comprehensive market analysis summaries that flow through the
analysis-to-execution pipeline.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

from .enums import MarketBias, PatternName, SignalType, TrendDirection


@dataclass
class TradeSignal:
    """Represents a single trade signal generated by pattern detection."""
    symbol: str
    signal_type: SignalType
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float
    pattern: PatternName
    timeframe: str
    reason: str
    risk_reward: float
    metadata: Dict = field(default_factory=dict)


@dataclass
class AIDecision:
    """AI-generated decision after evaluating market conditions and signals."""
    direction: SignalType
    confidence: float
    market_bias: MarketBias
    entry_zone: tuple
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward: Optional[float] = None
    confirmation_factors: List[str] = field(default_factory=list)
    rejection_reasons: List[str] = field(default_factory=list)


@dataclass
class MarketAnalysis:
    """Comprehensive analysis result for a single timeframe."""
    timeframe: str
    trend: TrendDirection
    bias: MarketBias
    atr: Optional[float] = None
    atr_percentile: Optional[float] = None
    volatility_regime: Optional[str] = None
    structure_breaks: List = field(default_factory=list)
    sr_levels: List = field(default_factory=list)
    momentum: Optional[str] = None
    signals: List[TradeSignal] = field(default_factory=list)
